self-hosted-runner:
  labels:
    - linux-aarch64-a2-1
    - linux-aarch64-a2-2
    - linux-aarch64-a2-4
    - linux-aarch64-a2-8
    - linux-aarch64-a2-16
    - linux-aarch64-a3-1
    - linux-aarch64-a3-2
    - linux-aarch64-a3-4
    - linux-aarch64-a3-8
    - linux-aarch64-a3-16
